name: extract

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  merge_group:
  workflow_dispatch:

jobs:
  extract-dependencies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17

      - uses: gradle/actions/setup-gradle@v4

      - name: Check Spotless
        run: |
          cd gradle/android-all-jars-metadata-extractor && \
          ./gradlew spotlessCheck && cd../..

      - name: Update shell scripts
        run: |
          cd gradle/android-all-jars-metadata-extractor && \
          ./gradlew updateAndroidAllJarsMetadata && cd ../..

      - name: Check new shell script' changes
        run: |
          git status -s && [ $? -ne 0 ] && \
          echo "Uncommitted changes detected. Exiting the pipeline." && \
          exit 1

      - name: Print metadata for robolectric-bazel
        run: |
          cd gradle/android-all-jars-metadata-extractor && \
          ./gradlew retrieveRobolectricVersionForBazel && cd ../..
           

